version: '3'
networks:
  esnet1:
    external: true
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - esnet1

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.2.2
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - esnet1

  nimbus:
    image: storm:1.2.2
    hostname: stormnimbus
    container_name: stormnimbus
    command: storm nimbus
    volumes:
      - ./logs:/logs
    depends_on:
      - zookeeper
    networks:
      - esnet1
    ports:
      - 6627:6627
    deploy:
      restart_policy:
        condition: on-failure
  supervisor:
    image: storm:1.2.2
    hostname: stormsupervisor
    container_name: stormsupervisor
    command: storm supervisor -c storm.log.dir="/logs"
    depends_on:
      - zookeeper
      - kafka
      - nimbus
    networks:
      - esnet1

  elasticsearch:
    image: elasticsearch:7.2.0
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

    tty : true
    networks:
      - esnet1

  loglistenercombine:
    image: combined-services
    depends_on:
      - zookeeper
      - kafka
      - nimbus
      - supervisor
    networks:
      - esnet1

  logstats:
    image: log-stats
    depends_on:
      - loglistenercombine
    networks:
      - esnet1
    environment:
      KAFKA.BOOTSTRAPSERVER: kafka:9092

  logflow:
    image: log-flow
    depends_on:
      - loglistenercombine
    networks:
      - esnet1

